const { rollAction, rollDie, rollInRange } = require('../src/services/dice.service')
const ShipService = require('../src/services/ship.service')
const ConsumableService = require('../src/services/consumable.service')
const LogService = require('../src/services/log.service')
// Mission content (planet, events, dc, failureConsequence...) is generated by
// src/engine/missionGenerator.js via src/utils/random.js. That module is left
// unmocked here on purpose — we want the real generation logic under test —
// but we seed it so the 25 mission templates seeded by bootstrapPlayer come
// out identically every run. Without this, tests that assert on specific
// generated mission content (e.g. "this template has an HP_LOSS event")
// would be flaky: they'd only pass whenever unseeded Math.random happened to
// roll the right outcome.
const { setSeed, resetSeed } = require('../src/utils/random')

// Chosen because, with the current data files, it deterministically produces:
//  - template #1 (ROUTINE): 2 events (fixed by ROUTINE's eventCount; content-independent)
//  - template #6 (STANDARD): RECON, COMBAT, SURVIVAL — the last with failureConsequence HP_LOSS
//  - template #11 (HARD): RECON(dc18), RECON(dc17), COMBAT(dc18, FORCED_DEPARTURE), SURVIVAL
// If the mission data files (data/*.json) ever change, this seed may need to
// be re-picked so those templates keep matching the assertions below.
const MISSION_SEED = 15

jest.mock('../src/db/pool', () => ({ pool: { connect: jest.fn(), query: jest.fn() } }))
jest.mock('../src/services/dice.service')
jest.mock('../src/services/log.service')
jest.mock('../src/services/ship.service')
jest.mock('../src/services/consumable.service')

const { pool } = require('../src/db/pool')
const GameService = require('../src/services/game.service')

// Fake in-memory Postgres client: each test gets a "fresh" connection
// (bootstrapPlayer starts from an empty state), but the state is shared between all
// calls of a same test to allow chaining startMission -> syncGame etc.
function createFakeClient() {
  const state = {
    players: [],
    candidates: [],
    recruits: [],
    missionTemplates: [],
    missionInstances: [],
    ships: [],
    logEntries: [],
  }
  let nextInstanceId = 1000
  // Postgres implicitly casts text parameters to the column type (int);
  // recruit ids sometimes pass through as strings via rowToRecruit, so we compare with relaxed typing.
  const sameId = (a, b) => String(a) === String(b)

  const query = jest.fn(async (sql, params = []) => {
    const s = sql.replace(/\s+/g, ' ').trim()

    if (s === 'BEGIN' || s === 'COMMIT' || s === 'ROLLBACK') return { rows: [] }

    // players
    if (s.includes('INSERT INTO players')) {
      const [id, display_name] = params
      const player = {
        id, display_name, wallet: 10000,
        max_recruits: 5, max_available_missions: 5,
        next_candidate_id: 1, next_recruit_id: 1, next_ship_id: 1,
      }
      state.players.push(player)
      return { rows: [player] }
    }
    if (s.includes('SELECT max_recruits, max_available_missions FROM players')) {
      const p = state.players.find(p => p.id === params[0])
      return { rows: p ? [{ max_recruits: p.max_recruits, max_available_missions: p.max_available_missions }] : [] }
    }
    if (s.includes('UPDATE players SET next_candidate_id = $1 WHERE id = $2')) {
      const [nextId, id] = params
      Object.assign(state.players.find(p => p.id === id), { next_candidate_id: nextId })
      return { rows: [] }
    }
    if (s.includes("UPDATE players SET next_candidate_id = 1 WHERE id = $1")) {
      Object.assign(state.players.find(p => p.id === params[0]), { next_candidate_id: 1 })
      return { rows: [] }
    }
    if (s.includes('UPDATE players SET next_ship_id = next_ship_id + 1')) {
      state.players.find(p => p.id === params[0]).next_ship_id++
      return { rows: [] }
    }
    if (s.includes('UPDATE players SET next_recruit_id = next_recruit_id + 1')) {
      state.players.find(p => p.id === params[0]).next_recruit_id++
      return { rows: [] }
    }
    if (s.includes('UPDATE players SET last_tick_at = NOW()')) {
      return { rows: [] }
    }
    if (s === 'SELECT * FROM players WHERE id = $1') {
      return { rows: state.players.filter(p => p.id === params[0]) }
    }
    if (s === 'SELECT wallet FROM players WHERE id = $1 FOR UPDATE') {
      return { rows: state.players.filter(p => p.id === params[0]).map(p => ({ wallet: p.wallet })) }
    }
    if (s === 'UPDATE players SET wallet = $1 WHERE id = $2') {
      const [wallet, id] = params
      Object.assign(state.players.find(p => p.id === id), { wallet })
      return { rows: [] }
    }

    // candidates
    if (s.includes('INSERT INTO candidates')) {
      const [id, player_id, name, job_title, archetype, hp, max_hp, attributes, perks, flaws, personality] = params
      state.candidates.push({
        id, player_id, name, job_title, archetype, hp, max_hp,
        attributes: JSON.parse(attributes), perks: JSON.parse(perks), flaws: JSON.parse(flaws), personality,
      })
      return { rows: [] }
    }
    if (s === 'SELECT COUNT(*)::int AS count FROM candidates WHERE player_id = $1') {
      return { rows: [{ count: state.candidates.filter(c => c.player_id === params[0]).length }] }
    }
    if (s === 'SELECT id FROM candidates WHERE player_id = $1 ORDER BY id LIMIT 1') {
      const list = state.candidates.filter(c => c.player_id === params[0]).sort((a, b) => a.id - b.id)
      return { rows: list.length ? [{ id: list[0].id }] : [] }
    }
    if (s === 'SELECT * FROM candidates WHERE player_id = $1 AND id = $2') {
      return { rows: state.candidates.filter(c => c.player_id === params[0] && c.id === params[1]) }
    }
    if (s === 'DELETE FROM candidates WHERE player_id = $1 AND id = $2') {
      state.candidates = state.candidates.filter(c => !(c.player_id === params[0] && c.id === params[1]))
      return { rows: [] }
    }
    if (s === 'DELETE FROM candidates WHERE player_id = $1') {
      state.candidates = state.candidates.filter(c => c.player_id !== params[0])
      return { rows: [] }
    }
    if (s === 'SELECT * FROM candidates WHERE player_id = $1 ORDER BY id') {
      return { rows: state.candidates.filter(c => c.player_id === params[0]).sort((a, b) => a.id - b.id) }
    }

    // recruits
    if (s.startsWith('SELECT * FROM recruits WHERE player_id = $1 AND id = $2')) {
      return { rows: state.recruits.filter(r => r.player_id === params[0] && sameId(r.id, params[1])) }
    }
    if (s.includes('UPDATE recruits SET hp = $1, status = $2')) {
      const [hp, status, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r) Object.assign(r, { hp, status })
      return { rows: [] }
    }
    if (s.includes("UPDATE recruits SET status = $1") && s.includes("status != 'dead'")) {
      const [status, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r && r.status !== 'dead') r.status = status
      return { rows: [] }
    }
    if (s === 'SELECT name FROM recruits WHERE player_id = $1 AND id = $2') {
      const r = state.recruits.find(r => r.player_id === params[0] && sameId(r.id, params[1]))
      return { rows: r ? [{ name: r.name }] : [] }
    }
    if (s === 'SELECT COUNT(*)::int AS count FROM recruits WHERE player_id = $1') {
      return { rows: [{ count: state.recruits.filter(r => r.player_id === params[0]).length }] }
    }
    if (s.includes('INSERT INTO recruits')) {
      const [id, player_id, name, job_title, hp, max_hp, attributes, perks, flaws, personality] = params
      state.recruits.push({
        id, player_id, name, job_title, status: 'available', hp, max_hp,
        attributes: JSON.parse(attributes), perks: JSON.parse(perks), flaws: JSON.parse(flaws), personality,
      })
      return { rows: [] }
    }
    if (s.includes('UPDATE recruits SET name = $1')) {
      const [name, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r) r.name = name
      return { rows: r ? [r] : [] }
    }
    if (s === 'SELECT * FROM recruits WHERE player_id = $1 ORDER BY id') {
      return { rows: state.recruits.filter(r => r.player_id === params[0]).sort((a, b) => a.id - b.id) }
    }

    // mission_templates
    if (s === 'SELECT COUNT(*)::int AS count FROM mission_templates') {
      return { rows: [{ count: state.missionTemplates.length }] }
    }
    if (s.includes('INSERT INTO mission_templates')) {
      const [id, name, description, difficulty, events, planet] = params
      const tpl = {
        id, name, description, difficulty,
        events: JSON.parse(events),
        planet: planet ? JSON.parse(planet) : null,
      }
      const existing = state.missionTemplates.find(t => t.id === id)
      if (existing) Object.assign(existing, tpl)
      else state.missionTemplates.push(tpl)
      return { rows: [] }
    }
    if (s === 'SELECT * FROM mission_templates WHERE id = $1') {
      return { rows: state.missionTemplates.filter(t => t.id === params[0]) }
    }
    if (s === 'SELECT * FROM mission_templates ORDER BY id') {
      return { rows: [...state.missionTemplates].sort((a, b) => a.id - b.id) }
    }

    // mission_instances
    if (s === 'SELECT * FROM mission_instances WHERE player_id = $1 AND template_id = $2') {
      return { rows: state.missionInstances.filter(i => i.player_id === params[0] && i.template_id === params[1]) }
    }
    if (s.includes('INSERT INTO mission_instances')) {
      const [player_id, template_id, ship_id, travel_segment_ms, events_segment_ms] = params
      const instance = {
        id: nextInstanceId++, player_id, template_id, ship_id, status: 'in_progress', phase: 'EN_ROUTE',
        progress: 0, started_at: new Date(), failed: false, reward_forfeited: false, current_event_index: 0,
        event_results: [], forced_return: false, return_started_at: null, progress_at_return: null,
        travel_segment_ms, events_segment_ms,
      }
      state.missionInstances.push(instance)
      return { rows: [instance] }
    }
    if (s === 'DELETE FROM mission_instances WHERE id = $1') {
      state.missionInstances = state.missionInstances.filter(i => i.id !== params[0])
      return { rows: [] }
    }
    if (s.includes('forced_return = TRUE, return_started_at = NOW(), progress_at_return = progress')) {
      const i = state.missionInstances.find(i => i.id === params[0])
      Object.assign(i, { forced_return: true, return_started_at: new Date(), progress_at_return: i.progress, phase: 'RETURN' })
      return { rows: [] }
    }
    if (s === 'SELECT * FROM mission_instances WHERE player_id = $1 AND status = $2') {
      return { rows: state.missionInstances.filter(i => i.player_id === params[0] && i.status === params[1]) }
    }
    if (s.includes('forced_return = TRUE, return_started_at = NOW(), progress_at_return = $5')) {
      const [failed, rewardForfeited, currentEventIndex, eventResults, progress, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        failed, reward_forfeited: rewardForfeited, current_event_index: currentEventIndex,
        event_results: JSON.parse(eventResults), forced_return: true, return_started_at: new Date(),
        progress_at_return: progress, phase: 'RETURN', progress,
      })
      return { rows: [] }
    }
    if (s.includes("phase = 'COMPLETED', progress = 100, status = 'failed'")) {
      const [failed, rewardForfeited, currentEventIndex, eventResults, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        failed, reward_forfeited: rewardForfeited, current_event_index: currentEventIndex,
        event_results: JSON.parse(eventResults), phase: 'COMPLETED', progress: 100, status: 'failed',
      })
      return { rows: [] }
    }
    if (s.includes("UPDATE mission_instances SET phase = 'COMPLETED', progress = 100, failed = $1")) {
      const [failed, rewardForfeited, currentEventIndex, eventResults, status, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        phase: 'COMPLETED', progress: 100, failed, reward_forfeited: rewardForfeited,
        current_event_index: currentEventIndex, event_results: JSON.parse(eventResults), status,
      })
      return { rows: [] }
    }
    if (s.includes('UPDATE mission_instances SET phase = $1, progress = $2, failed = $3')) {
      const [phase, progress, failed, rewardForfeited, currentEventIndex, eventResults, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        phase, progress, failed, reward_forfeited: rewardForfeited,
        current_event_index: currentEventIndex, event_results: JSON.parse(eventResults),
      })
      return { rows: [] }
    }
    if (s === 'SELECT * FROM mission_instances WHERE player_id = $1') {
      return { rows: state.missionInstances.filter(i => i.player_id === params[0]) }
    }

    // ships (only the raw read used by buildGameState — the rest goes through ShipService, mocked)
    if (s === 'SELECT * FROM ships WHERE player_id = $1 AND deleted_at IS NULL ORDER BY id') {
      return { rows: state.ships.filter(sh => sh.player_id === params[0]) }
    }

    // log_entries (writes go through log.service, mocked; only the read is direct)
    if (s.includes('SELECT tag, message, mission_id AS "missionId" FROM log_entries')) {
      return { rows: state.logEntries.filter(l => l.player_id === params[0]) }
    }

    throw new Error(`Query not handled by the fake test client: ${s}`)
  })

  return { client: { query, release: jest.fn() }, state }
}

describe('GameService', () => {
  let state

  afterAll(() => {
    resetSeed()
  })

  beforeEach(() => {
    jest.clearAllMocks()
    setSeed(MISSION_SEED)
    const fake = createFakeClient()
    state = fake.state
    pool.connect.mockResolvedValue(fake.client)
    pool.query.mockImplementation((sql, params) => fake.client.query(sql, params))

    rollInRange.mockReturnValue(0)
    rollDie.mockReturnValue(3)
    LogService.buildPhaseLogs.mockReturnValue({ mission: [], global: [] })
    LogService.buildEventResultLogs.mockReturnValue({ mission: [], global: [] })
    LogService.insertLogEntries.mockResolvedValue(undefined)

    ShipService.getHangar.mockResolvedValue(null)
    ShipService.createHangar.mockResolvedValue({})
    ShipService.createDockingStation.mockResolvedValue({})
    ShipService.getShips.mockResolvedValue([])
    ConsumableService.consumeFromShipInventory.mockResolvedValue(null)
    ShipService.createShip.mockResolvedValue({})
  })

  describe('initGame / bootstrapPlayer', () => {
    test('creates a player, docks a starter ship, generates 5 candidates then recruits one', async () => {
      await GameService.initGame()

      expect(state.players).toHaveLength(1)
      expect(ShipService.createHangar).toHaveBeenCalledWith(expect.anything(), 1)
      expect(ShipService.createDockingStation).toHaveBeenCalledWith(expect.anything(), 1, 5)
      expect(ShipService.createShip).toHaveBeenCalledWith(
        expect.anything(), 1, expect.objectContaining({ rarity: 'common' }),
      )
      expect(state.candidates).toHaveLength(4)
      expect(state.recruits).toHaveLength(1)
      expect(state.recruits[0].status).toBe('available')
    })

    test('seeds the 25 mission templates from missions.json', async () => {
      await GameService.initGame()
      expect(state.missionTemplates).toHaveLength(25)
    })

    test('persiste le planet object (avec tags) de chaque modèle de mission généré', async () => {
      // Reproduces exactly what seedMissionTemplates() does internally (same
      // seed, same loadData()/generateMission() calls) so we can assert the
      // persisted planet matches what the generator actually produced,
      // instead of asserting on hardcoded tag values.
      setSeed(MISSION_SEED)
      const { loadData } = require('../src/dataLoader')
      const { generateMission } = require('../src/engine/missionGenerator')
      const SEED_DIFFICULTIES = [
        'ROUTINE', 'ROUTINE', 'ROUTINE', 'ROUTINE', 'ROUTINE',
        'STANDARD', 'STANDARD', 'STANDARD', 'STANDARD', 'STANDARD',
        'HARD', 'HARD', 'HARD', 'HARD', 'HARD', 'HARD',
        'PERILOUS', 'PERILOUS', 'PERILOUS', 'PERILOUS', 'PERILOUS',
        'EPIC', 'EPIC', 'EPIC', 'EPIC', 'EPIC',
      ]
      const data = loadData()
      const expectedMissions = SEED_DIFFICULTIES.map(difficulty => generateMission(data, { difficulty }))

      setSeed(MISSION_SEED)
      await GameService.initGame()

      expect(state.missionTemplates).toHaveLength(25)
      state.missionTemplates
        .sort((a, b) => a.id - b.id)
        .forEach((tpl, i) => {
          expect(tpl.planet).not.toBeNull()
          expect(Array.isArray(tpl.planet.tags)).toBe(true)
          expect(tpl.planet.tags).toEqual(expectedMissions[i].planet.tags)
          expect(tpl.planet.name).toEqual(expectedMissions[i].planet.name)
        })
    })

    test('est idempotent : un second appel ne recrée ni joueur ni recrue supplémentaire', async () => {
      await GameService.initGame()
      await GameService.initGame()

      expect(state.players).toHaveLength(1)
      expect(state.recruits).toHaveLength(1)
      expect(state.candidates).toHaveLength(4)
    })
  })

  describe('getGameState', () => {
    test('exposes the recruits, candidates, available missions and player limits', async () => {
      const result = await GameService.getGameState()

      expect(result.player).toEqual({ maxNumberOfRecruits: 5, maxAvailableMissions: 5 })
      expect(result.recruits).toHaveLength(1)
      expect(result.candidates).toHaveLength(4)
      expect(result.missions.length).toBeLessThanOrEqual(5)
      expect(result.missions.every(m => m.status === 'available')).toBe(true)
    })
  })

  describe('hireCandidate', () => {
    test('turns a candidate into an available recruit and removes it from the candidates', async () => {
      await GameService.initGame()
      const candidateId = state.candidates[0].id

      const result = await GameService.hireCandidate(String(candidateId))

      expect(result.error).toBeUndefined()
      expect(result.recruit.status).toBe('available')
      expect(state.candidates.find(c => c.id === candidateId)).toBeUndefined()
      expect(state.recruits).toHaveLength(2)
    })

    test("fails when the maximum number of recruits is reached", async () => {
      await GameService.initGame()
      state.players[0].max_recruits = 1
      const candidateId = state.candidates[0].id

      const result = await GameService.hireCandidate(String(candidateId))

      expect(result.error).toBe('Recruitment failed')
      expect(state.recruits).toHaveLength(1)
    })

    test('fails when the candidate cannot be found', async () => {
      await GameService.initGame()

      const result = await GameService.hireCandidate('99999')

      expect(result.error).toBe('Recruitment failed')
    })
  })

  describe('startMission', () => {
    async function bootstrapWithDockedShip(crew = [1]) {
      await GameService.initGame()
      const recruitId = state.recruits[0].id
      const ship = { id: 1, player_id: 1, crew, status: 'docked', deleted_at: null }
      ShipService.getShip.mockResolvedValue(ship)
      return { recruitId, ship }
    }

    test("launches the mission, switches the crew to in_mission and the ship to in_mission", async () => {
      const { recruitId } = await bootstrapWithDockedShip()
      state.recruits[0].id = 1 // aligns with the crew of the simulated ship

      const result = await GameService.startMission(1, 1)

      expect(result.error).toBeUndefined()
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'in_mission')
      expect(state.recruits.find(r => r.id === 1).status).toBe('in_mission')
      expect(state.missionInstances).toHaveLength(1)
      expect(state.missionInstances[0]).toMatchObject({ template_id: 1, ship_id: 1, phase: 'EN_ROUTE', progress: 0 })
    })

    test('refuses an unknown mission', async () => {
      await bootstrapWithDockedShip()
      const result = await GameService.startMission(9999, 1)
      expect(result.error).toBe('Mission not found')
    })

    test('refuses to relaunch a mission that is already in progress', async () => {
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      await GameService.startMission(1, 1)

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe('Mission already in progress')
    })

    test('refuses a ship that cannot be found', async () => {
      await GameService.initGame()
      ShipService.getShip.mockResolvedValue(null)

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe('Ship not found')
    })

    test("refuses a ship that is not docked", async () => {
      await GameService.initGame()
      ShipService.getShip.mockResolvedValue({ id: 1, crew: [1], status: 'in_mission', deleted_at: null })

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe("The ship is not docked")
    })

    test('refuses a ship with no crew', async () => {
      await GameService.initGame()
      ShipService.getShip.mockResolvedValue({ id: 1, crew: [], status: 'docked', deleted_at: null })

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe("The ship has no crew")
    })

    test("refuses if a crew member is not available", async () => {
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      state.recruits[0].status = 'in_mission'

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe("At least one crew member is not available")
    })

    test('consuming a valid speed-boost item shortens the stored travel segment', async () => {
      const { travelSegmentMs, eventsSegmentMs } = require('../src/domain/mission')
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      ConsumableService.getConsumable.mockResolvedValue({
        id: 5, assigned_to_ship: 1, effect: 'SPEED_BOOST', effect_data: { multiplier: 2 },
      })
      ConsumableService.consumeFromShipInventory.mockResolvedValue({ id: 5 })

      const result = await GameService.startMission(1, 1, 5)

      expect(result.error).toBeUndefined()
      expect(ConsumableService.consumeFromShipInventory).toHaveBeenCalledWith(expect.anything(), 1, 'SPEED_BOOST')
      const eventCount = state.missionTemplates.find(t => t.id === 1).events.length
      expect(state.missionInstances[0].travel_segment_ms).toBe(travelSegmentMs(eventCount, 200))
      expect(state.missionInstances[0].events_segment_ms).toBe(eventsSegmentMs(eventCount))
    })

    test('refuses when the speed-boost item is not in this ship\'s inventory', async () => {
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      ConsumableService.getConsumable.mockResolvedValue({ id: 5, assigned_to_ship: 999, effect: 'SPEED_BOOST' })

      const result = await GameService.startMission(1, 1, 5)

      expect(result.error).toBe("Speed-boost item not found in this ship's inventory")
      expect(state.missionInstances).toHaveLength(0)
      expect(ConsumableService.consumeFromShipInventory).not.toHaveBeenCalled()
    })

    test('without a speedConsumableId, no consumable lookup happens and speed defaults to the ship stat', async () => {
      const { travelSegmentMs } = require('../src/domain/mission')
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1

      await GameService.startMission(1, 1)

      expect(ConsumableService.getConsumable).not.toHaveBeenCalled()
      const eventCount = state.missionTemplates.find(t => t.id === 1).events.length
      expect(state.missionInstances[0].travel_segment_ms).toBe(travelSegmentMs(eventCount, 100))
    })
  })

  describe('syncGame — mission resolution', () => {
    async function launchMission(templateId, crewId = 1) {
      await GameService.initGame()
      state.recruits[0].id = crewId
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [crewId], status: 'docked', deleted_at: null })
      await GameService.startMission(templateId, 1)
      return state.missionInstances[0]
    }

    test('a successful mission returns the crew and the ship to base once time has elapsed', async () => {
      const instance = await launchMission(1) // template ROUTINE (seed 15): 2 events, NO_REWARD consequence only (fixed by difficulty-tables.json)
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000) // well past 2 * 15s
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 20 })

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.status).toBe('success')
      expect(updated.phase).toBe('COMPLETED')
      expect(updated.event_results).toHaveLength(2)
      expect(updated.event_results.every(r => r.success)).toBe(true)
      expect(state.recruits.find(r => r.id === 1).status).toBe('available')
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')

      const totalReward = updated.event_results.reduce((sum, r) => sum + r.rewardEarned.amount, 0)
      expect(state.players[0].wallet).toBe(10000 + totalReward)
    })

    test('an HP_LOSS failure hurts the recruit but still returns the crew and the ship to base', async () => {
      const instance = await launchMission(6) // template STANDARD (seed 15): RECON, COMBAT, SURVIVAL(HP_LOSS)
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 1, bonus: 0, diceNotation: '—', total: 1 }) // systematic failure
      rollDie.mockReturnValue(4)

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(recruit.hp).toBeLessThan(recruit.max_hp)
      expect(updated.event_results.some(r => r.consequence === 'HP_LOSS' && r.hpLost === 4)).toBe(true)
      // no event of this mission sets `failed`, the recruit survives: the mission ends in success
      expect(updated.status).toBe('success')
      expect(recruit.status).toBe('available')
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })

    test('the recruit dying on the last HP_LOSS event ends the mission in failure', async () => {
      const instance = await launchMission(6)
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })
      state.recruits.find(r => r.id === 1).hp = 3 // dies on the first HP_LOSS failure (rollDie -> 3)
      rollDie.mockReturnValue(3)

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(recruit.status).toBe('dead')
      expect(recruit.hp).toBe(0)
      expect(updated.status).toBe('failed')
      expect(updated.event_results.at(-1).recruitDied).toBe(true)
      // failed mission without destruction of the ship: it should still return to port
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
      expect(state.players[0].wallet).toBe(10000) // a failed mission earns no credits
    })

    test('a FORCED_DEPARTURE failure immediately switches the mission to RETURN phase', async () => {
      const instance = await launchMission(11) // template HARD (seed 15): RECON(dc18),RECON(dc17),COMBAT(dc18,FORCED_DEPARTURE),SURVIVAL
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // 1st RECON success (dc18)
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // 2nd RECON success (dc17)
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // COMBAT failure -> FORCED_DEPARTURE

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.phase).toBe('RETURN')
      expect(updated.forced_return).toBe(true)
      expect(updated.failed).toBe(true)
      expect(updated.current_event_index).toBe(3) // stops after the 3rd event (index 2 + 1)
      expect(updated.event_results).toHaveLength(3)
      expect(ShipService.updateShipStatus).not.toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })

    test('once the return trip has elapsed, a FORCED_DEPARTURE failure returns the ship and the surviving recruit to base', async () => {
      await launchMission(11)
      state.missionInstances[0].started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // RECON success
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // INFILTRATION success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // COMBAT failure -> FORCED_DEPARTURE
      await GameService.syncGame() // switches to RETURN

      await GameService.syncGame() // the return trip has already elapsed (progress_at_return already at 100)
      const updated = state.missionInstances[0]
      const recruit = state.recruits.find(r => r.id === 1)

      expect(updated.phase).toBe('COMPLETED')
      expect(updated.status).toBe('failed')
      expect(recruit.status).toBe('available')
      expect(ShipService.destroyShip).not.toHaveBeenCalled()
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })
  })

  describe('syncGame — consumable effects', () => {
    async function launchMission(templateId, crewId = 1) {
      await GameService.initGame()
      state.recruits[0].id = crewId
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [crewId], status: 'docked', deleted_at: null })
      await GameService.startMission(templateId, 1)
      return state.missionInstances[0]
    }

    test('an ATTRIBUTE_BOOST consumable in the ship inventory grants advantage only on the matching attribute', async () => {
      const instance = await launchMission(1) // ROUTINE (seed 15): BREACH[learning] dc15, INFILTRATION[agility] dc10
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 20 })
      ConsumableService.consumeFromShipInventory.mockImplementation((client, shipId, effect, matcher) => {
        if (effect === 'ATTRIBUTE_BOOST' && matcher && matcher({ attribute: 'learning' })) {
          return Promise.resolve({ id: 42, effect_data: { advantage: 1 } })
        }
        return Promise.resolve(null)
      })

      await GameService.syncGame()

      expect(rollAction).toHaveBeenNthCalledWith(1, expect.any(Number), 1) // learning event: boosted
      expect(rollAction).toHaveBeenNthCalledWith(2, expect.any(Number), 0) // agility event: no matching item
    })

    test('a HEAL consumable revives a recruit that would otherwise die, instead of ending the mission', async () => {
      // STANDARD (seed 15): RECON[perception]dc14 HP_LOSS, COMBAT[agility]dc13 NO_REWARD, COMBAT[might]dc13 HP_LOSS.
      // Only the first event is made to fail, isolating the one lethal hit the HEAL item should intercept.
      const instance = await launchMission(6)
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // RECON(HP_LOSS) failure
        .mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 20 })     // remaining events succeed
      state.recruits.find(r => r.id === 1).hp = 3
      rollDie.mockReturnValue(3) // lethal hit, exactly at the recruit's remaining HP
      ConsumableService.consumeFromShipInventory.mockImplementation((client, shipId, effect) =>
        Promise.resolve(effect === 'HEAL' ? { id: 7 } : null))

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(recruit.status).not.toBe('dead')
      expect(recruit.hp).toBe(recruit.max_hp)
      expect(updated.status).not.toBe('failed')
    })

    test('a SHIP_DAMAGE failure auto-repairs when a REPAIR consumable is available, and the mission continues', async () => {
      // PERILOUS (seed 15): RECON[perception]dc20 HP_LOSS, BREACH[learning]dc30 FORCED_DEPARTURE,
      // BREACH[learning]dc30 SHIP_DAMAGE, INFILTRATION[agility]dc26 FORCED_DEPARTURE, INFILTRATION[agility]dc23 HP_LOSS
      const instance = await launchMission(17)
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // RECON success
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // BREACH(FORCED_DEPARTURE) success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // BREACH(SHIP_DAMAGE) failure
        .mockReturnValue({ d20: 30, bonus: 0, diceNotation: '—', total: 30 })     // remaining events succeed
      rollDie.mockReturnValue(3)
      ShipService.damageShip.mockResolvedValue({ id: 1, status: 'broken', stats: { durability: 0, max_durability: 10 } })
      ConsumableService.consumeFromShipInventory.mockImplementation((client, shipId, effect) =>
        Promise.resolve(effect === 'REPAIR' ? { id: 9 } : null))

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(ShipService.damageShip).toHaveBeenCalledWith(expect.anything(), 1, 1, 3)
      expect(ShipService.repairShip).toHaveBeenCalledWith(expect.anything(), 1, 1)
      expect(updated.forced_return).toBe(false)
      expect(updated.event_results.find(r => r.consequence === 'SHIP_DAMAGE').shipAutoRepaired).toBe(true)
    })

    test('a SHIP_DAMAGE failure without a REPAIR item breaks the ship and forces a return', async () => {
      const instance = await launchMission(17)
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // RECON success
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // BREACH(FORCED_DEPARTURE) success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // BREACH(SHIP_DAMAGE) failure
      rollDie.mockReturnValue(10)
      ShipService.damageShip.mockResolvedValue({ id: 1, status: 'broken', stats: { durability: 0, max_durability: 10 } })

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(ShipService.repairShip).not.toHaveBeenCalled()
      expect(updated.phase).toBe('RETURN')
      expect(updated.forced_return).toBe(true)
      expect(updated.event_results.at(-1).shipBroken).toBe(true)
    })
  })

  describe('stopMission', () => {
    test('releases crew and ship then deletes the mission in progress', async () => {
      await GameService.initGame()
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(1, 1)

      const result = await GameService.stopMission(1)

      expect(result.error).toBeUndefined()
      expect(state.missionInstances).toHaveLength(0)
      expect(state.recruits.find(r => r.id === 1).status).toBe('available')
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })

    test('reports an error when no active mission matches', async () => {
      await GameService.initGame()
      const result = await GameService.stopMission(1)
      expect(result.error).toBe('No active mission')
    })
  })

  describe('forceReturnMission', () => {
    test('triggers a forced return on a mission in progress', async () => {
      await GameService.initGame()
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(1, 1)

      const result = await GameService.forceReturnMission(1)

      expect(result.error).toBeUndefined()
      expect(state.missionInstances[0].forced_return).toBe(true)
      expect(state.missionInstances[0].phase).toBe('RETURN')
    })

    test('refuses if no active mission matches', async () => {
      await GameService.initGame()
      const result = await GameService.forceReturnMission(1)
      expect(result.error).toBe('No active mission')
    })

    test('refuses a second forced return once RETURN phase is reached', async () => {
      await GameService.initGame()
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(1, 1)
      await GameService.forceReturnMission(1)

      const result = await GameService.forceReturnMission(1)
      expect(result.error).toBe('Return already in progress or mission completed')
    })
  })

  describe('refreshCandidates', () => {
    test('replaces all existing candidates with a new batch', async () => {
      await GameService.initGame()
      const previousIds = state.candidates.map(c => c.id)

      await GameService.refreshCandidates(3)

      expect(state.candidates).toHaveLength(3)
      expect(state.candidates.map(c => c.id)).not.toEqual(previousIds)
      expect(state.players[0].next_candidate_id).toBe(4)
    })
  })

  describe('renameRecruit', () => {
    test('renames an existing recruit', async () => {
      await GameService.initGame()
      const recruitId = state.recruits[0].id

      const result = await GameService.renameRecruit(String(recruitId), 'New Name')

      expect(result.error).toBeUndefined()
      expect(result.recruit.name).toBe('New Name')
      expect(state.recruits[0].name).toBe('New Name')
    })

    test('reports an error when the recruit cannot be found', async () => {
      await GameService.initGame()
      const result = await GameService.renameRecruit('99999', 'New Name')
      expect(result.error).toBe('Recruit not found')
    })
  })

  describe('getMissionLogs', () => {
    test('returns the logs of the requested mission for the default player', async () => {
      state.logEntries.push(
        { player_id: 1, mission_id: 1, tag: '[SYS]', message: 'Departure' },
        { player_id: 1, mission_id: 2, tag: '[SYS]', message: 'Other mission' },
      )
      pool.query.mockImplementation(async (sql, params) => {
        if (sql.includes('FROM log_entries') && sql.includes('mission_id = $2')) {
          return {
            rows: state.logEntries
              .filter(l => l.player_id === params[0] && l.mission_id === params[1])
              .map(({ tag, message }) => ({ tag, message })),
          }
        }
        throw new Error(`Query not handled: ${sql}`)
      })

      const logs = await GameService.getMissionLogs(1)

      expect(logs).toEqual([{ tag: '[SYS]', message: 'Departure' }])
    })
  })
})
