const { rollAction, rollDie, rollInRange } = require('../src/services/dice.service')
const ShipService = require('../src/services/ship.service')
const ConsumableService = require('../src/services/consumable.service')
const LogService = require('../src/services/log.service')
// Mission content (planet, events, dc, failureConsequence...) is generated by
// src/engine/missionGenerator.js via src/utils/random.js. That module is left
// unmocked here on purpose — we want the real generation logic under test —
// but we seed it so the 25 mission templates seeded by bootstrapPlayer come
// out identically every run. Without this, tests that assert on specific
// generated mission content (e.g. "this template has an HP_LOSS event")
// would be flaky: they'd only pass whenever unseeded Math.random happened to
// roll the right outcome.
const { setSeed, resetSeed } = require('../src/utils/random')

// Mission templates are now generated in weighted-random batches of 5 (see
// game.service.js's generateMissionBatch), so a seed no longer pins specific
// content to specific template ids the way the old fixed 25-template seed
// did. This seed is kept only so batch-generation itself (count, shape,
// reproducibility) is deterministic across runs; tests that need specific
// event content build synthetic templates directly (see seedTemplate/
// buildEvent below) rather than relying on what a given seed happens to
// produce.
const MISSION_SEED = 15

jest.mock('../src/db/pool', () => ({ pool: { connect: jest.fn(), query: jest.fn() } }))
jest.mock('../src/services/dice.service')
jest.mock('../src/services/log.service')
jest.mock('../src/services/ship.service')
jest.mock('../src/services/consumable.service')

const { pool } = require('../src/db/pool')
const GameService = require('../src/services/game.service')

// Fake in-memory Postgres client: each test gets a "fresh" connection
// (bootstrapPlayer starts from an empty state), but the state is shared between all
// calls of a same test to allow chaining startMission -> syncGame etc.
function createFakeClient() {
  const state = {
    players: [],
    candidates: [],
    recruits: [],
    missionTemplates: [],
    missionInstances: [],
    ships: [],
    logEntries: [],
  }
  let nextInstanceId = 1000
  // Postgres implicitly casts text parameters to the column type (int);
  // recruit ids sometimes pass through as strings via rowToRecruit, so we compare with relaxed typing.
  const sameId = (a, b) => String(a) === String(b)

  const query = jest.fn(async (sql, params = []) => {
    const s = sql.replace(/\s+/g, ' ').trim()

    if (s === 'BEGIN' || s === 'COMMIT' || s === 'ROLLBACK') return { rows: [] }

    // players
    if (s.includes('INSERT INTO players')) {
      const [id, display_name] = params
      const player = {
        id, display_name, wallet: 10000, tokens: 0,
        max_recruits: 5, max_available_missions: 5,
        next_candidate_id: 1, next_recruit_id: 1, next_ship_id: 1,
        next_template_id: 1, mission_refresh_at: null, shop_refresh_at: null,
      }
      state.players.push(player)
      return { rows: [player] }
    }
    if (s.includes('SELECT max_recruits, max_available_missions, wallet, tokens FROM players')) {
      const p = state.players.find(p => p.id === params[0])
      return { rows: p ? [{ max_recruits: p.max_recruits, max_available_missions: p.max_available_missions, wallet: p.wallet, tokens: p.tokens }] : [] }
    }
    if (s.includes('UPDATE players SET next_candidate_id = $1 WHERE id = $2')) {
      const [nextId, id] = params
      Object.assign(state.players.find(p => p.id === id), { next_candidate_id: nextId })
      return { rows: [] }
    }
    if (s.includes("UPDATE players SET next_candidate_id = 1 WHERE id = $1")) {
      Object.assign(state.players.find(p => p.id === params[0]), { next_candidate_id: 1 })
      return { rows: [] }
    }
    if (s.includes('UPDATE players SET next_ship_id = next_ship_id + 1')) {
      state.players.find(p => p.id === params[0]).next_ship_id++
      return { rows: [] }
    }
    if (s.includes('UPDATE players SET next_recruit_id = next_recruit_id + 1')) {
      state.players.find(p => p.id === params[0]).next_recruit_id++
      return { rows: [] }
    }
    if (s.includes('UPDATE players SET last_tick_at = NOW()')) {
      return { rows: [] }
    }
    if (s === 'SELECT * FROM players WHERE id = $1') {
      return { rows: state.players.filter(p => p.id === params[0]) }
    }
    if (s === 'SELECT wallet, tokens FROM players WHERE id = $1 FOR UPDATE') {
      return { rows: state.players.filter(p => p.id === params[0]).map(p => ({ wallet: p.wallet, tokens: p.tokens })) }
    }
    if (s === 'UPDATE players SET wallet = $1, tokens = $2 WHERE id = $3') {
      const [wallet, tokens, id] = params
      Object.assign(state.players.find(p => p.id === id), { wallet, tokens })
      return { rows: [] }
    }

    // candidates
    if (s.includes('INSERT INTO candidates')) {
      const [id, player_id, name, job_title, archetype, hp, max_hp, attributes, perks, flaws, personality] = params
      state.candidates.push({
        id, player_id, name, job_title, archetype, hp, max_hp,
        attributes: JSON.parse(attributes), perks: JSON.parse(perks), flaws: JSON.parse(flaws), personality,
      })
      return { rows: [] }
    }
    if (s === 'SELECT COUNT(*)::int AS count FROM candidates WHERE player_id = $1') {
      return { rows: [{ count: state.candidates.filter(c => c.player_id === params[0]).length }] }
    }
    if (s === 'SELECT id FROM candidates WHERE player_id = $1 ORDER BY id LIMIT 1') {
      const list = state.candidates.filter(c => c.player_id === params[0]).sort((a, b) => a.id - b.id)
      return { rows: list.length ? [{ id: list[0].id }] : [] }
    }
    if (s === 'SELECT * FROM candidates WHERE player_id = $1 AND id = $2') {
      return { rows: state.candidates.filter(c => c.player_id === params[0] && c.id === params[1]) }
    }
    if (s === 'DELETE FROM candidates WHERE player_id = $1 AND id = $2') {
      state.candidates = state.candidates.filter(c => !(c.player_id === params[0] && c.id === params[1]))
      return { rows: [] }
    }
    if (s === 'DELETE FROM candidates WHERE player_id = $1') {
      state.candidates = state.candidates.filter(c => c.player_id !== params[0])
      return { rows: [] }
    }
    if (s === 'SELECT * FROM candidates WHERE player_id = $1 ORDER BY id') {
      return { rows: state.candidates.filter(c => c.player_id === params[0]).sort((a, b) => a.id - b.id) }
    }

    // recruits
    if (s.startsWith('SELECT * FROM recruits WHERE player_id = $1 AND id = $2')) {
      return { rows: state.recruits.filter(r => r.player_id === params[0] && sameId(r.id, params[1])) }
    }
    if (s.includes('UPDATE recruits SET hp = $1, max_hp = $2, status = $3')) {
      const [hp, max_hp, status, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r) Object.assign(r, { hp, max_hp, status })
      return { rows: [] }
    }
    if (s.includes('UPDATE recruits SET hp = $1, status = $2')) {
      const [hp, status, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r) Object.assign(r, { hp, status })
      return { rows: [] }
    }
    if (s.includes("UPDATE recruits SET status = $1") && s.includes("status != 'dead'")) {
      const [status, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r && r.status !== 'dead') r.status = status
      return { rows: [] }
    }
    if (s === 'SELECT name FROM recruits WHERE player_id = $1 AND id = $2') {
      const r = state.recruits.find(r => r.player_id === params[0] && sameId(r.id, params[1]))
      return { rows: r ? [{ name: r.name }] : [] }
    }
    if (s === 'SELECT COUNT(*)::int AS count FROM recruits WHERE player_id = $1') {
      return { rows: [{ count: state.recruits.filter(r => r.player_id === params[0]).length }] }
    }
    if (s.includes('INSERT INTO recruits')) {
      const [id, player_id, name, job_title, hp, max_hp, original_max_hp, attributes, perks, flaws, personality] = params
      state.recruits.push({
        id, player_id, name, job_title, status: 'available', hp, max_hp, original_max_hp,
        attributes: JSON.parse(attributes), perks: JSON.parse(perks), flaws: JSON.parse(flaws), personality,
      })
      return { rows: [] }
    }
    if (s.includes('UPDATE recruits SET name = $1')) {
      const [name, playerId, id] = params
      const r = state.recruits.find(r => r.player_id === playerId && sameId(r.id, id))
      if (r) r.name = name
      return { rows: r ? [r] : [] }
    }
    if (s === 'SELECT * FROM recruits WHERE player_id = $1 ORDER BY id') {
      return { rows: state.recruits.filter(r => r.player_id === params[0]).sort((a, b) => a.id - b.id) }
    }

    // mission_templates
    if (s === 'SELECT COUNT(*)::int AS count FROM mission_templates') {
      return { rows: [{ count: state.missionTemplates.length }] }
    }
    if (s.includes('INSERT INTO mission_templates')) {
      const [id, name, description, difficulty, events, planet] = params
      const tpl = {
        id, name, description, difficulty,
        events: JSON.parse(events),
        planet: planet ? JSON.parse(planet) : null,
      }
      const existing = state.missionTemplates.find(t => t.id === id)
      if (existing) Object.assign(existing, tpl)
      else state.missionTemplates.push(tpl)
      return { rows: [] }
    }
    if (s === 'SELECT * FROM mission_templates WHERE id = $1') {
      return { rows: state.missionTemplates.filter(t => t.id === params[0]) }
    }
    if (s === 'SELECT * FROM mission_templates ORDER BY id') {
      return { rows: [...state.missionTemplates].sort((a, b) => a.id - b.id) }
    }
    if (s === 'SELECT id FROM mission_templates') {
      return { rows: state.missionTemplates.map(t => ({ id: t.id })) }
    }
    if (s === 'DELETE FROM mission_templates WHERE id = ANY($1::int[])') {
      const ids = new Set(params[0])
      state.missionTemplates = state.missionTemplates.filter(t => !ids.has(t.id))
      return { rows: [] }
    }
    if (s === 'SELECT DISTINCT template_id FROM mission_instances WHERE player_id = $1') {
      const ids = new Set(state.missionInstances.filter(i => i.player_id === params[0]).map(i => i.template_id))
      return { rows: [...ids].map(template_id => ({ template_id })) }
    }
    if (s === 'UPDATE players SET next_template_id = $1, mission_refresh_at = $2 WHERE id = $3') {
      const [next_template_id, mission_refresh_at, id] = params
      Object.assign(state.players.find(p => p.id === id), { next_template_id, mission_refresh_at })
      return { rows: [] }
    }

    // mission_instances
    if (s === 'SELECT * FROM mission_instances WHERE player_id = $1 AND template_id = $2') {
      return { rows: state.missionInstances.filter(i => i.player_id === params[0] && i.template_id === params[1]) }
    }
    if (s.includes('INSERT INTO mission_instances')) {
      const [player_id, template_id, ship_id, travel_segment_ms, events_segment_ms] = params
      const instance = {
        id: nextInstanceId++, player_id, template_id, ship_id, status: 'in_progress', phase: 'EN_ROUTE',
        progress: 0, started_at: new Date(), failed: false, reward_forfeited: false, current_event_index: 0,
        event_results: [], forced_return: false, return_started_at: null, progress_at_return: null,
        travel_segment_ms, events_segment_ms,
      }
      state.missionInstances.push(instance)
      return { rows: [instance] }
    }
    if (s === 'DELETE FROM mission_instances WHERE id = $1') {
      state.missionInstances = state.missionInstances.filter(i => i.id !== params[0])
      return { rows: [] }
    }
    if (s.includes('forced_return = TRUE, return_started_at = NOW(), progress_at_return = progress')) {
      const i = state.missionInstances.find(i => i.id === params[0])
      Object.assign(i, { forced_return: true, return_started_at: new Date(), progress_at_return: i.progress, phase: 'RETURN' })
      return { rows: [] }
    }
    if (s === 'SELECT * FROM mission_instances WHERE player_id = $1 AND status = $2') {
      return { rows: state.missionInstances.filter(i => i.player_id === params[0] && i.status === params[1]) }
    }
    if (s.includes('forced_return = TRUE, return_started_at = NOW(), progress_at_return = $5')) {
      const [failed, rewardForfeited, currentEventIndex, eventResults, progress, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        failed, reward_forfeited: rewardForfeited, current_event_index: currentEventIndex,
        event_results: JSON.parse(eventResults), forced_return: true, return_started_at: new Date(),
        progress_at_return: progress, phase: 'RETURN', progress,
      })
      return { rows: [] }
    }
    if (s.includes("phase = 'COMPLETED', progress = 100, status = 'failed'")) {
      const [failed, rewardForfeited, currentEventIndex, eventResults, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        failed, reward_forfeited: rewardForfeited, current_event_index: currentEventIndex,
        event_results: JSON.parse(eventResults), phase: 'COMPLETED', progress: 100, status: 'failed',
      })
      return { rows: [] }
    }
    if (s.includes("UPDATE mission_instances SET phase = 'COMPLETED', progress = 100, failed = $1")) {
      const [failed, rewardForfeited, currentEventIndex, eventResults, status, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        phase: 'COMPLETED', progress: 100, failed, reward_forfeited: rewardForfeited,
        current_event_index: currentEventIndex, event_results: JSON.parse(eventResults), status,
      })
      return { rows: [] }
    }
    if (s.includes('UPDATE mission_instances SET phase = $1, progress = $2, failed = $3')) {
      const [phase, progress, failed, rewardForfeited, currentEventIndex, eventResults, id] = params
      const i = state.missionInstances.find(i => i.id === id)
      Object.assign(i, {
        phase, progress, failed, reward_forfeited: rewardForfeited,
        current_event_index: currentEventIndex, event_results: JSON.parse(eventResults),
      })
      return { rows: [] }
    }
    if (s === 'SELECT * FROM mission_instances WHERE player_id = $1') {
      return { rows: state.missionInstances.filter(i => i.player_id === params[0]) }
    }

    // ships (only the raw read used by buildGameState — the rest goes through ShipService, mocked)
    if (s === 'SELECT * FROM ships WHERE player_id = $1 AND deleted_at IS NULL ORDER BY id') {
      return { rows: state.ships.filter(sh => sh.player_id === params[0]) }
    }

    // log_entries (writes go through log.service, mocked; only the read is direct)
    if (s.includes('SELECT tag, message, mission_id AS "missionId" FROM log_entries')) {
      return { rows: state.logEntries.filter(l => l.player_id === params[0]) }
    }

    throw new Error(`Query not handled by the fake test client: ${s}`)
  })

  return { client: { query, release: jest.fn() }, state }
}

// Mission-resolution tests (HP_LOSS chains, FORCED_DEPARTURE, COMBAT,
// SHIP_DAMAGE, consumable interactions...) need specific, stable event
// content to assert against. Under the old fixed 25-template seed, that
// content came from generateMission() at a known template id with a known
// RNG seed. Now that templates are generated in weighted-random batches of
// 5, that coupling is gone — chasing a seed that "happens" to produce a
// given difficulty/event combo at a given id would be fragile and would
// silently break again the next time data/*.json changes. Instead, these
// tests build synthetic templates directly, in the same shape
// missionGenerator.js produces, and insert them straight into the fake
// client's state (at ids the natural weighted batch won't use, since a
// fresh batch only ever occupies ids 1-5).
function buildEvent({ id = 'test-event', beat = 'EXECUTION', type, attribute = null, dc = 10, failureConsequence = null, rewardAmount = 100 }) {
  return {
    id,
    beat,
    type,
    attribute,
    dc,
    description: `Test ${type} event`,
    reward: { type: 'CREDITS', amount: rewardAmount, description: 'Test reward' },
    failureConsequence,
  }
}

function seedTemplate(state, { id, difficulty = 'STANDARD', events, name = 'Test Mission', description = 'A test mission.', planet = null }) {
  const template = { id, name, description, difficulty, events, planet }
  const existing = state.missionTemplates.find(t => t.id === id)
  if (existing) Object.assign(existing, template)
  else state.missionTemplates.push(template)
  return template
}

describe('GameService', () => {
  let state

  afterAll(() => {
    resetSeed()
  })

  afterEach(() => {
    jest.useRealTimers()
  })

  beforeEach(() => {
    jest.clearAllMocks()
    setSeed(MISSION_SEED)
    const fake = createFakeClient()
    state = fake.state
    pool.connect.mockResolvedValue(fake.client)
    pool.query.mockImplementation((sql, params) => fake.client.query(sql, params))

    rollInRange.mockReturnValue(0)
    rollDie.mockReturnValue(3)
    LogService.buildPhaseLogs.mockReturnValue({ mission: [], global: [] })
    LogService.buildEventResultLogs.mockReturnValue({ mission: [], global: [] })
    LogService.buildCombatRoundLog.mockReturnValue({ tag: '[SYS]', message: '', missionId: undefined })
    LogService.buildCombatEventLogs.mockReturnValue({ mission: [], global: [] })
    LogService.insertLogEntries.mockResolvedValue(undefined)

    ShipService.getHangar.mockResolvedValue(null)
    ShipService.createHangar.mockResolvedValue({})
    ShipService.createDockingStation.mockResolvedValue({})
    ShipService.getShips.mockResolvedValue([])
    ConsumableService.consumeFromShipInventory.mockResolvedValue(null)
    ConsumableService.countShipInventoryEffect.mockResolvedValue(0)
    ShipService.createShip.mockResolvedValue({})
  })

  describe('initGame / bootstrapPlayer', () => {
    test('creates a player, docks a starter ship, generates 5 candidates then recruits one', async () => {
      await GameService.initGame()

      expect(state.players).toHaveLength(1)
      expect(ShipService.createHangar).toHaveBeenCalledWith(expect.anything(), 1)
      expect(ShipService.createDockingStation).toHaveBeenCalledWith(expect.anything(), 1, 5)
      expect(ShipService.createShip).toHaveBeenCalledWith(
        expect.anything(), 1, expect.objectContaining({ rarity: 'common' }),
      )
      expect(state.candidates).toHaveLength(4)
      expect(state.recruits).toHaveLength(1)
      expect(state.recruits[0].status).toBe('available')
    })

    test('seeds an initial batch of 5 mission templates', async () => {
      await GameService.initGame()
      expect(state.missionTemplates).toHaveLength(5)
    })

    test('persists the planet object (with tags) of each generated mission template', async () => {
      // Reproduces exactly what generateMissionBatch() does internally (same
      // seed, same loadData()/generateMission() calls, same call count) so we
      // can assert the persisted planet matches what the generator actually
      // produced, instead of asserting on hardcoded tag values.
      setSeed(MISSION_SEED)
      const { loadData } = require('../src/dataLoader')
      const { generateMission } = require('../src/engine/missionGenerator')
      const data = loadData()
      const expectedMissions = Array.from({ length: 5 }, () => generateMission(data, {}))

      setSeed(MISSION_SEED)
      await GameService.initGame()

      expect(state.missionTemplates).toHaveLength(5)
      state.missionTemplates
        .sort((a, b) => a.id - b.id)
        .forEach((tpl, i) => {
          expect(tpl.planet).not.toBeNull()
          expect(Array.isArray(tpl.planet.tags)).toBe(true)
          expect(tpl.planet.tags).toEqual(expectedMissions[i].planet.tags)
          expect(tpl.planet.name).toEqual(expectedMissions[i].planet.name)
        })
    })

    test('is idempotent: a second call does not recreate a player or extra recruit', async () => {
      await GameService.initGame()
      await GameService.initGame()

      expect(state.players).toHaveLength(1)
      expect(state.recruits).toHaveLength(1)
      expect(state.candidates).toHaveLength(4)
    })
  })

  describe('mission batch refresh (lazy, wall-clock aligned)', () => {
    test('does not regenerate the batch or move next_template_id/mission_refresh_at before the next 15-minute boundary', async () => {
      jest.useFakeTimers({ doNotFake: ['nextTick', 'setImmediate'] })
      jest.setSystemTime(new Date('2026-01-01T10:00:00Z'))
      await GameService.initGame()
      const firstBatchIds = state.missionTemplates.map(t => t.id).sort((a, b) => a - b)
      const refreshAtAfterFirst = state.players[0].mission_refresh_at
      const nextTemplateIdAfterFirst = state.players[0].next_template_id

      jest.setSystemTime(new Date('2026-01-01T10:14:59Z')) // still inside the same 15-minute window
      await GameService.initGame()
      await GameService.getGameState()
      await GameService.syncGame()

      expect(state.missionTemplates.map(t => t.id).sort((a, b) => a - b)).toEqual(firstBatchIds)
      expect(state.players[0].mission_refresh_at).toEqual(refreshAtAfterFirst)
      expect(state.players[0].next_template_id).toBe(nextTemplateIdAfterFirst)
    })

    test('at the next wall-clock boundary, discards only unstarted templates from the previous batch and generates a fresh batch of 5', async () => {
      jest.useFakeTimers({ doNotFake: ['nextTick', 'setImmediate'] })
      jest.setSystemTime(new Date('2026-01-01T10:00:00Z'))
      await GameService.initGame()
      const firstBatchIds = state.missionTemplates.map(t => t.id).sort((a, b) => a - b)
      expect(firstBatchIds).toHaveLength(5)

      // Start one template from the first batch so it should survive the refresh.
      const startedId = firstBatchIds[0]
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(startedId, 1)

      jest.setSystemTime(new Date('2026-01-01T10:15:00Z')) // exactly the next 15-minute boundary
      await GameService.initGame()

      const templateIds = state.missionTemplates.map(t => t.id).sort((a, b) => a - b)
      // the started template persists...
      expect(templateIds).toContain(startedId)
      // ...but the other, never-started templates from the first batch are gone
      const discardedIds = firstBatchIds.filter(id => id !== startedId)
      for (const id of discardedIds) {
        expect(templateIds).not.toContain(id)
      }
      // a fresh batch of exactly 5 new, unstarted templates now exists alongside the started one
      const startedTemplateIds = new Set(state.missionInstances.map(i => i.template_id))
      const unstarted = state.missionTemplates.filter(t => !startedTemplateIds.has(t.id))
      expect(unstarted).toHaveLength(5)
      expect(state.missionTemplates).toHaveLength(6) // 1 persisted (started) + 5 new
      // ids are never reused: the counter continues past the highest id ever issued
      expect(state.players[0].next_template_id).toBe(Math.max(...firstBatchIds) + 1 + 5)
      expect(new Date(state.players[0].mission_refresh_at).toISOString()).toBe('2026-01-01T10:15:00.000Z')
    })

    test('a completed (succeeded) template also survives a refresh, exactly like an in-progress one', async () => {
      jest.useFakeTimers({ doNotFake: ['nextTick', 'setImmediate'] })
      jest.setSystemTime(new Date('2026-01-01T10:00:00Z'))
      await GameService.initGame()
      const firstBatchIds = state.missionTemplates.map(t => t.id).sort((a, b) => a - b)
      const completedId = firstBatchIds[0]

      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(completedId, 1)
      state.missionInstances[0].started_at = new Date(Date.now() - 60 * 60 * 1000) // well past the mission's duration
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 9999 }) // trivially wins/succeeds every event, combat included
      await GameService.syncGame()
      expect(state.missionInstances[0].status).toBe('success')

      jest.setSystemTime(new Date('2026-01-01T10:15:00Z')) // next 15-minute boundary
      await GameService.initGame()

      expect(state.missionTemplates.map(t => t.id)).toContain(completedId)
    })

    // Integration check spanning the mission-batching (discard-unstarted-on-
    // refresh) and mission-history (`mission list --completed`) features
    // together: a mission started just before a refresh boundary must stay
    // visible in the live view while in progress, survive the refresh that
    // discards its unstarted siblings, still be visible in the live view
    // and in history once it crosses that boundary, then move from the live
    // view into history (never disappearing from either data source) once
    // it actually completes.
    test('a mission started right before a refresh boundary remains visible in the live view while running, survives the refresh, and moves into history (without ever vanishing from both) once it completes', async () => {
      jest.useFakeTimers({ doNotFake: ['nextTick', 'setImmediate'] })
      jest.setSystemTime(new Date('2026-01-01T10:00:00Z'))
      await GameService.initGame()
      const firstBatchIds = state.missionTemplates.map(t => t.id).sort((a, b) => a - b)
      const startedId = firstBatchIds[0]

      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(startedId, 1)

      // Still inside the same window: live view shows it in progress, and
      // history already reports the same live status too.
      let live = await GameService.getGameState()
      expect(live.missions.find(m => m.id === startedId)).toMatchObject({ status: 'in_progress' })
      let history = await GameService.getMissionHistory()
      expect(history.find(m => m.id === startedId)).toMatchObject({ status: 'in_progress' })

      // Cross the wall-clock boundary: unstarted siblings from the first
      // batch get discarded and replaced, but the started template must
      // persist and keep reporting 'in_progress' in both views. Uses
      // initGame() (like the sibling tests above), not syncGame(), so the
      // mission-resolution clock (15s/event) doesn't also race ahead of the
      // 15-minute refresh clock and resolve the mission early — the two are
      // deliberately kept independent here to isolate what's under test.
      jest.setSystemTime(new Date('2026-01-01T10:15:00Z'))
      await GameService.initGame()

      live = await GameService.getGameState()
      expect(live.missions.map(m => m.id)).toContain(startedId)
      expect(live.missions.find(m => m.id === startedId)).toMatchObject({ status: 'in_progress' })
      const discardedIds = firstBatchIds.filter(id => id !== startedId)
      for (const id of discardedIds) {
        expect(live.missions.map(m => m.id)).not.toContain(id)
      }

      history = await GameService.getMissionHistory()
      expect(history.find(m => m.id === startedId)).toMatchObject({ status: 'in_progress' })

      // Let the mission actually finish, still after the refresh boundary.
      state.missionInstances[0].started_at = new Date(Date.now() - 60 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 9999 })
      await GameService.syncGame()
      expect(state.missionInstances[0].status).toBe('success')

      // Once resolved, it must drop out of the live batch view (only
      // available/in_progress templates are shown there) but must still be
      // reachable, tagged 'success', from the full history — never absent
      // from both at once.
      live = await GameService.getGameState()
      expect(live.missions.some(m => m.id === startedId)).toBe(false)

      history = await GameService.getMissionHistory()
      expect(history.find(m => m.id === startedId)).toMatchObject({ status: 'success' })

      // A further refresh (a second 15-minute boundary) must not discard it
      // from history either, since it was started (and completed).
      jest.setSystemTime(new Date('2026-01-01T10:30:00Z'))
      await GameService.initGame()
      history = await GameService.getMissionHistory()
      expect(history.find(m => m.id === startedId)).toMatchObject({ status: 'success' })
    })
  })

  describe('getGameState', () => {
    test('exposes the recruits, candidates, available missions and player limits', async () => {
      const result = await GameService.getGameState()

      expect(result.player).toEqual({ maxNumberOfRecruits: 5, maxAvailableMissions: 5, credits: 10000, tokens: 0 })
      expect(result.recruits).toHaveLength(1)
      expect(result.candidates).toHaveLength(4)
      expect(result.missions.length).toBeLessThanOrEqual(5)
      expect(result.missions.every(m => m.status === 'available')).toBe(true)
    })
  })

  describe('hireCandidate', () => {
    test('turns a candidate into an available recruit and removes it from the candidates', async () => {
      await GameService.initGame()
      const candidateId = state.candidates[0].id

      const result = await GameService.hireCandidate(String(candidateId))

      expect(result.error).toBeUndefined()
      expect(result.recruit.status).toBe('available')
      expect(state.candidates.find(c => c.id === candidateId)).toBeUndefined()
      expect(state.recruits).toHaveLength(2)
    })

    test("fails when the maximum number of recruits is reached", async () => {
      await GameService.initGame()
      state.players[0].max_recruits = 1
      const candidateId = state.candidates[0].id

      const result = await GameService.hireCandidate(String(candidateId))

      expect(result.error).toBe('Recruitment failed')
      expect(state.recruits).toHaveLength(1)
    })

    test('fails when the candidate cannot be found', async () => {
      await GameService.initGame()

      const result = await GameService.hireCandidate('99999')

      expect(result.error).toBe('Recruitment failed')
    })
  })

  describe('startMission', () => {
    async function bootstrapWithDockedShip(crew = [1]) {
      await GameService.initGame()
      const recruitId = state.recruits[0].id
      const ship = { id: 1, player_id: 1, crew, status: 'docked', deleted_at: null }
      ShipService.getShip.mockResolvedValue(ship)
      return { recruitId, ship }
    }

    test("launches the mission, switches the crew to in_mission and the ship to in_mission", async () => {
      const { recruitId } = await bootstrapWithDockedShip()
      state.recruits[0].id = 1 // aligns with the crew of the simulated ship

      const result = await GameService.startMission(1, 1)

      expect(result.error).toBeUndefined()
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'in_mission')
      expect(state.recruits.find(r => r.id === 1).status).toBe('in_mission')
      expect(state.missionInstances).toHaveLength(1)
      expect(state.missionInstances[0]).toMatchObject({ template_id: 1, ship_id: 1, phase: 'EN_ROUTE', progress: 0 })
    })

    test('refuses an unknown mission', async () => {
      await bootstrapWithDockedShip()
      const result = await GameService.startMission(9999, 1)
      expect(result.error).toBe('Mission not found')
    })

    test('refuses to relaunch a mission that is already in progress', async () => {
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      await GameService.startMission(1, 1)

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe('Mission already in progress')
    })

    test('refuses a ship that cannot be found', async () => {
      await GameService.initGame()
      ShipService.getShip.mockResolvedValue(null)

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe('Ship not found')
    })

    test("refuses a ship that is not docked", async () => {
      await GameService.initGame()
      ShipService.getShip.mockResolvedValue({ id: 1, crew: [1], status: 'in_mission', deleted_at: null })

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe("The ship is not docked")
    })

    test('refuses a ship with no crew', async () => {
      await GameService.initGame()
      ShipService.getShip.mockResolvedValue({ id: 1, crew: [], status: 'docked', deleted_at: null })

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe("The ship has no crew")
    })

    test("refuses if a crew member is not available", async () => {
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      state.recruits[0].status = 'in_mission'

      const result = await GameService.startMission(1, 1)
      expect(result.error).toBe("At least one crew member is not available")
    })

    test('consuming a valid speed-boost item shortens the stored travel segment', async () => {
      const { travelSegmentMs, eventsSegmentMs } = require('../src/domain/mission')
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      ConsumableService.getConsumable.mockResolvedValue({
        id: 5, assigned_to_ship: 1, effect: 'SPEED_BOOST', effect_data: { multiplier: 2 },
      })
      ConsumableService.consumeFromShipInventory.mockResolvedValue({ id: 5 })

      const result = await GameService.startMission(1, 1, 5)

      expect(result.error).toBeUndefined()
      expect(ConsumableService.consumeFromShipInventory).toHaveBeenCalledWith(expect.anything(), 1, 'SPEED_BOOST')
      const eventCount = state.missionTemplates.find(t => t.id === 1).events.length
      expect(state.missionInstances[0].travel_segment_ms).toBe(travelSegmentMs(eventCount, 200))
      expect(state.missionInstances[0].events_segment_ms).toBe(eventsSegmentMs(eventCount))
    })

    test('refuses when the speed-boost item is not in this ship\'s inventory', async () => {
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1
      ConsumableService.getConsumable.mockResolvedValue({ id: 5, assigned_to_ship: 999, effect: 'SPEED_BOOST' })

      const result = await GameService.startMission(1, 1, 5)

      expect(result.error).toBe("Speed-boost item not found in this ship's inventory")
      expect(state.missionInstances).toHaveLength(0)
      expect(ConsumableService.consumeFromShipInventory).not.toHaveBeenCalled()
    })

    test('without a speedConsumableId, no consumable lookup happens and speed defaults to the ship stat', async () => {
      const { travelSegmentMs } = require('../src/domain/mission')
      await bootstrapWithDockedShip()
      state.recruits[0].id = 1

      await GameService.startMission(1, 1)

      expect(ConsumableService.getConsumable).not.toHaveBeenCalled()
      const eventCount = state.missionTemplates.find(t => t.id === 1).events.length
      expect(state.missionInstances[0].travel_segment_ms).toBe(travelSegmentMs(eventCount, 100))
    })
  })

  describe('syncGame — mission resolution', () => {
    async function launchSeededMission(templateDef, crewId = 1) {
      await GameService.initGame() // creates the natural batch first
      seedTemplate(state, templateDef) // ...then add the custom template, so it isn't discarded as an "unstarted leftover"
      state.recruits[0].id = crewId
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [crewId], status: 'docked', deleted_at: null })
      await GameService.startMission(templateDef.id, 1)
      return state.missionInstances[0]
    }

    // Custom template ids (100+) so they never collide with the natural
    // weighted-random batch, which only ever occupies ids 1-5 — see the
    // seedTemplate/buildEvent comment above.
    const TWO_EVENT_TEMPLATE_ID = 101
    const HP_LOSS_TEMPLATE_ID = 102
    const FORCED_DEPARTURE_TEMPLATE_ID = 103

    test('a successful mission returns the crew and the ship to base once time has elapsed', async () => {
      const instance = await launchSeededMission({
        id: TWO_EVENT_TEMPLATE_ID,
        difficulty: 'ROUTINE',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 10, failureConsequence: 'HP_LOSS', rewardAmount: 100 }),
          buildEvent({ id: 'e2', type: 'BREACH', attribute: 'engineering', dc: 10, failureConsequence: 'HP_LOSS', rewardAmount: 150 }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000) // well past the mission's duration
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 20 })

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.status).toBe('success')
      expect(updated.phase).toBe('COMPLETED')
      expect(updated.event_results).toHaveLength(2)
      expect(updated.event_results.every(r => r.success)).toBe(true)
      expect(state.recruits.find(r => r.id === 1).status).toBe('available')
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')

      const totalReward = updated.event_results.reduce((sum, r) => sum + r.rewardEarned.amount, 0)
      expect(state.players[0].wallet).toBe(10000 + totalReward)
      // ROUTINE tokenBase is 10; both of 2 events succeeded -> 10 * (0.5 + 2/2) = 15
      expect(state.players[0].tokens).toBe(15)
    })

    test('a failed mission leaves tokens unchanged', async () => {
      const instance = await launchSeededMission({
        id: HP_LOSS_TEMPLATE_ID,
        difficulty: 'STANDARD',
        events: [
          buildEvent({ id: 'e1', type: 'ENGINEERING', attribute: 'engineering', dc: 18, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'ENGINEERING', attribute: 'engineering', dc: 10, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e3', type: 'SURVIVAL', attribute: 'survival', dc: 20, failureConsequence: 'HP_LOSS' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })
      state.recruits.find(r => r.id === 1).hp = 3 // dies on the first HP_LOSS failure (rollDie -> 3)
      rollDie.mockReturnValue(3)

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.status).toBe('failed')
      expect(state.players[0].tokens).toBe(0)
    })

    test('a successful mission with a mix of passed and failed events awards the correctly-scaled token amount', async () => {
      // STANDARD tokenBase is 15, 3 events. 2 of 3 succeed, none of them
      // HP_LOSS-lethal, so the mission still ends in success:
      // 15 * (0.5 + 2/3) = 17.4999... -> rounds to 17
      const instance = await launchSeededMission({
        id: HP_LOSS_TEMPLATE_ID,
        difficulty: 'STANDARD',
        events: [
          buildEvent({ id: 'e1', type: 'ENGINEERING', attribute: 'engineering', dc: 5, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'ENGINEERING', attribute: 'engineering', dc: 5, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e3', type: 'SURVIVAL', attribute: 'survival', dc: 30, failureConsequence: 'HP_LOSS' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // e1 success
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // e2 success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // e3 failure (HP_LOSS)
      rollDie.mockReturnValue(4) // survivable HP loss

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.status).toBe('success')
      expect(updated.event_results.filter(r => r.success)).toHaveLength(2)
      expect(state.players[0].tokens).toBe(17)
    })

    // This is the one behavior most likely to look like a bug at review
    // time: reward_forfeited zeroes out credits but NOT tokens. That's
    // intentional — the token formula already prices in a bad event via the
    // success ratio, so there's no need to also zero it out the way credits
    // are. See tokenReward.js and the completeMission gating for the
    // reasoning.
    test('a successful-but-reward_forfeited mission still awards tokens, even though credits are zero', async () => {
      const instance = await launchSeededMission({
        id: TWO_EVENT_TEMPLATE_ID,
        difficulty: 'ROUTINE',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 30, failureConsequence: 'NO_REWARD', rewardAmount: 100 }),
          buildEvent({ id: 'e2', type: 'BREACH', attribute: 'engineering', dc: 5, failureConsequence: 'NO_REWARD', rewardAmount: 150 }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // e1 fails -> NO_REWARD, rewardForfeited = true
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // e2 succeeds

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.status).toBe('success')
      expect(updated.reward_forfeited).toBe(true)
      expect(state.players[0].wallet).toBe(10000) // credits are forfeited
      // ROUTINE tokenBase is 10; 1 of 2 events succeeded -> 10 * (0.5 + 1/2) = 10
      expect(state.players[0].tokens).toBe(10)
    })

    test('an HP_LOSS failure hurts the recruit but still returns the crew and the ship to base', async () => {
      const instance = await launchSeededMission({
        id: HP_LOSS_TEMPLATE_ID,
        difficulty: 'STANDARD',
        events: [
          buildEvent({ id: 'e1', type: 'ENGINEERING', attribute: 'engineering', dc: 18, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'ENGINEERING', attribute: 'engineering', dc: 10, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e3', type: 'SURVIVAL', attribute: 'survival', dc: 20, failureConsequence: 'HP_LOSS' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 1, bonus: 0, diceNotation: '—', total: 1 }) // systematic failure
      rollDie.mockReturnValue(4)

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(recruit.hp).toBeLessThan(recruit.max_hp)
      expect(updated.event_results.some(r => r.consequence === 'HP_LOSS' && r.hpLost === 4)).toBe(true)
      // no event of this mission sets `failed`, the recruit survives: the mission ends in success
      expect(updated.status).toBe('success')
      expect(recruit.status).toBe('available')
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })

    test('the recruit dying on an HP_LOSS event ends the mission in failure', async () => {
      const instance = await launchSeededMission({
        id: HP_LOSS_TEMPLATE_ID,
        difficulty: 'STANDARD',
        events: [
          buildEvent({ id: 'e1', type: 'ENGINEERING', attribute: 'engineering', dc: 18, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'ENGINEERING', attribute: 'engineering', dc: 10, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e3', type: 'SURVIVAL', attribute: 'survival', dc: 20, failureConsequence: 'HP_LOSS' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })
      state.recruits.find(r => r.id === 1).hp = 3 // dies on the first HP_LOSS failure (rollDie -> 3)
      rollDie.mockReturnValue(3)

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(recruit.status).toBe('dead')
      expect(recruit.hp).toBe(0)
      expect(updated.status).toBe('failed')
      expect(updated.event_results.at(-1).recruitDied).toBe(true)
      // failed mission without destruction of the ship: it should still return to port
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
      expect(state.players[0].wallet).toBe(10000) // a failed mission earns no credits
    })

    test('a FORCED_DEPARTURE failure immediately switches the mission to RETURN phase', async () => {
      const instance = await launchSeededMission({
        id: FORCED_DEPARTURE_TEMPLATE_ID,
        difficulty: 'HARD',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 17, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'RECON', attribute: 'perception', dc: 21, failureConsequence: 'FORCED_DEPARTURE' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // 1st RECON success (dc17)
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // 2nd RECON failure -> FORCED_DEPARTURE

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(updated.phase).toBe('RETURN')
      expect(updated.forced_return).toBe(true)
      expect(updated.failed).toBe(true)
      expect(updated.current_event_index).toBe(2) // stops after the 2nd event (index 1 + 1)
      expect(updated.event_results).toHaveLength(2)
      expect(ShipService.updateShipStatus).not.toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })

    test('once the return trip has elapsed, a FORCED_DEPARTURE failure returns the ship and the surviving recruit to base', async () => {
      await launchSeededMission({
        id: FORCED_DEPARTURE_TEMPLATE_ID,
        difficulty: 'HARD',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 17, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'RECON', attribute: 'perception', dc: 21, failureConsequence: 'FORCED_DEPARTURE' }),
        ],
      })
      state.missionInstances[0].started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 20, bonus: 0, diceNotation: '—', total: 20 }) // RECON success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // RECON failure -> FORCED_DEPARTURE
      await GameService.syncGame() // switches to RETURN

      await GameService.syncGame() // the return trip has already elapsed (progress_at_return already at 100)
      const updated = state.missionInstances[0]
      const recruit = state.recruits.find(r => r.id === 1)

      expect(updated.phase).toBe('COMPLETED')
      expect(updated.status).toBe('failed')
      expect(recruit.status).toBe('available')
      expect(ShipService.destroyShip).not.toHaveBeenCalled()
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })
  })

  describe('syncGame — COMBAT auto-battle', () => {
    // Custom template id (see the seedTemplate/buildEvent comment above):
    // RECON(HP_LOSS)[dc14], COMBAT, COMBAT.
    // The hired recruit (default 'specialized' archetype under the seeded mocks)
    // has agility 4, might 2 -> Guard 16.
    const COMBAT_TEMPLATE_ID = 106
    function seedCombatTemplate() {
      seedTemplate(state, {
        id: COMBAT_TEMPLATE_ID,
        difficulty: 'STANDARD',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 14, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'COMBAT' }),
          buildEvent({ id: 'e3', type: 'COMBAT' }),
        ],
      })
    }

    async function launchCombatMission(crewId = 1) {
      await GameService.initGame() // creates the natural batch first
      seedCombatTemplate() // ...then add the custom template, so it isn't discarded as an "unstarted leftover"
      state.recruits[0].id = crewId
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [crewId], status: 'docked', deleted_at: null })
      await GameService.startMission(COMBAT_TEMPLATE_ID, 1)
      return state.missionInstances[0]
    }

    test('the crew defeats the enemy: the event succeeds, the reward is earned, and one SYS log is written per round', async () => {
      const instance = await launchCombatMission()
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      // A single overwhelming roll: the RECON check succeeds, and in both
      // COMBAT events the recruit (tied on agility with the enemy, so acting
      // first) one-shots the enemy before it ever gets a turn.
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 60 })
      rollInRange.mockReturnValue(0) // enemy Guard 0, Might primary (still tied vs recruit's agility 4)

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(updated.status).toBe('success')
      expect(updated.event_results).toHaveLength(3)
      const combatResults = updated.event_results.filter(r => r.combat)
      expect(combatResults).toHaveLength(2)
      expect(combatResults.every(r => r.enemyDefeated && r.success)).toBe(true)
      expect(recruit.hp).toBe(recruit.max_hp) // the enemy never got a turn
      expect(LogService.buildCombatRoundLog).toHaveBeenCalledTimes(2) // one round per COMBAT event
      expect(LogService.buildCombatEventLogs).toHaveBeenCalledTimes(2)
    })

    test('the crew loses a COMBAT event: the mission is forced to return and the recruit permanently loses 1 max HP', async () => {
      const instance = await launchCombatMission()
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 17, bonus: 0, diceNotation: '—', total: 17 })
      // Enemy Agility primary (6, faster than the recruit's 4) so it always
      // strikes first, and its roll (17) beats the recruit's Guard (16) for a
      // clamped-to-3 hit every round; the crew's roll (17) never beats the
      // enemy's rolled Guard (25), so it can never fight back. The recruit
      // grinds down over several rounds until finally knocked out once.
      rollInRange.mockReturnValue(25)
      ConsumableService.countShipInventoryEffect.mockResolvedValue(0) // no HEAL available

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(updated.phase).toBe('RETURN')
      expect(updated.forced_return).toBe(true)
      expect(updated.failed).toBe(true)
      expect(updated.current_event_index).toBe(2) // stops after the 2nd event (RECON success, then COMBAT loss)
      expect(updated.event_results.at(-1).consequence).toBe('FORCED_DEPARTURE')
      expect(recruit.max_hp).toBe(25) // 26 -> 25, permanently, from the single knockout suffered
      expect(recruit.hp).toBe(25) // patched back up to the new max once the fight ends
      expect(recruit.status).not.toBe('dead')
    })

    test('a HEAL consumable intercepts a would-be knockout during combat, preventing that knockout\'s permanent injury', async () => {
      const instance = await launchCombatMission()
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      const recruit = state.recruits.find(r => r.id === 1)
      recruit.hp = 5 // one big hit would otherwise knock them out
      // Enemy Agility primary (6) so it acts first and hits hard (total 999);
      // Guard is rolled at 25 (irrelevant here since 999 clears it easily), so
      // the crew (going second) then finishes the enemy off the same round.
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 999 })
      rollInRange.mockReturnValue(25)
      ConsumableService.countShipInventoryEffect.mockResolvedValue(1) // one HEAL charge available

      await GameService.syncGame()
      const finalRecruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]
      const combatResult = updated.event_results.find(r => r.combat)

      expect(ConsumableService.consumeFromShipInventory).toHaveBeenCalledWith(expect.anything(), 1, 'HEAL')
      expect(finalRecruit.max_hp).toBe(26) // no permanent reduction: the HEAL charge intercepted the only knockout
      expect(finalRecruit.hp).toBe(26)
      expect(combatResult.enemyDefeated).toBe(true)
    })

    test('a knockout that drops max HP to half the original (or below) kills the recruit', async () => {
      const instance = await launchCombatMission()
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      const recruit = state.recruits.find(r => r.id === 1)
      recruit.max_hp = 4
      recruit.hp = 3 // original_max_hp is still 26 from hiring, so half of it is 13
      rollAction.mockReturnValue({ d20: 17, bonus: 0, diceNotation: '—', total: 17 })
      rollInRange.mockReturnValue(25) // enemy strikes first and hits for a clamped 3 damage
      ConsumableService.countShipInventoryEffect.mockResolvedValue(0)

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(recruit.status).toBe('dead')
      expect(recruit.hp).toBe(0)
      expect(recruit.max_hp).toBe(3) // 4 -> 3, still recorded even though the recruit died
      expect(updated.failed).toBe(true)
      expect(updated.event_results.at(-1).recruitsDied).toEqual(['1'])
    })
  })

  describe('syncGame — consumable effects', () => {
    async function launchSeededMission(templateDef, crewId = 1) {
      await GameService.initGame() // creates the natural batch first
      seedTemplate(state, templateDef) // ...then add the custom template, so it isn't discarded as an "unstarted leftover"
      state.recruits[0].id = crewId
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [crewId], status: 'docked', deleted_at: null })
      await GameService.startMission(templateDef.id, 1)
      return state.missionInstances[0]
    }

    const ATTRIBUTE_BOOST_TEMPLATE_ID = 107
    const HEAL_TEMPLATE_ID = 108
    const SHIP_DAMAGE_TEMPLATE_ID = 109

    test('an ATTRIBUTE_BOOST consumable in the ship inventory grants advantage only on the matching attribute', async () => {
      const instance = await launchSeededMission({
        id: ATTRIBUTE_BOOST_TEMPLATE_ID,
        difficulty: 'ROUTINE',
        events: [
          buildEvent({ id: 'e1', type: 'BREACH', attribute: 'learning', dc: 15, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'INFILTRATION', attribute: 'agility', dc: 10, failureConsequence: 'HP_LOSS' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction.mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 20 })
      ConsumableService.consumeFromShipInventory.mockImplementation((client, shipId, effect, matcher) => {
        if (effect === 'ATTRIBUTE_BOOST' && matcher && matcher({ attribute: 'learning' })) {
          return Promise.resolve({ id: 42, effect_data: { advantage: 1 } })
        }
        return Promise.resolve(null)
      })

      await GameService.syncGame()

      expect(rollAction).toHaveBeenNthCalledWith(1, expect.any(Number), 1) // learning event: boosted
      expect(rollAction).toHaveBeenNthCalledWith(2, expect.any(Number), 0) // agility event: no matching item
    })

    test('a HEAL consumable revives a recruit that would otherwise die, instead of ending the mission', async () => {
      // Only the first event is made to fail, isolating the one lethal hit the HEAL item should intercept.
      const instance = await launchSeededMission({
        id: HEAL_TEMPLATE_ID,
        difficulty: 'STANDARD',
        events: [
          buildEvent({ id: 'e1', type: 'ENGINEERING', attribute: 'engineering', dc: 18, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'ENGINEERING', attribute: 'engineering', dc: 10, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e3', type: 'SURVIVAL', attribute: 'survival', dc: 20, failureConsequence: 'HP_LOSS' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // ENGINEERING(HP_LOSS) failure
        .mockReturnValue({ d20: 20, bonus: 0, diceNotation: '—', total: 20 })     // remaining events succeed
      state.recruits.find(r => r.id === 1).hp = 3
      rollDie.mockReturnValue(3) // lethal hit, exactly at the recruit's remaining HP
      ConsumableService.consumeFromShipInventory.mockImplementation((client, shipId, effect) =>
        Promise.resolve(effect === 'HEAL' ? { id: 7 } : null))

      await GameService.syncGame()
      const recruit = state.recruits.find(r => r.id === 1)
      const updated = state.missionInstances[0]

      expect(recruit.status).not.toBe('dead')
      expect(recruit.hp).toBe(recruit.max_hp)
      expect(updated.status).not.toBe('failed')
    })

    test('a SHIP_DAMAGE failure auto-repairs when a REPAIR consumable is available, and the mission continues', async () => {
      const instance = await launchSeededMission({
        id: SHIP_DAMAGE_TEMPLATE_ID,
        difficulty: 'PERILOUS',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 20, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'BREACH', attribute: 'learning', dc: 30, failureConsequence: 'FORCED_DEPARTURE' }),
          buildEvent({ id: 'e3', type: 'BREACH', attribute: 'learning', dc: 30, failureConsequence: 'SHIP_DAMAGE' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // RECON success
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // BREACH(FORCED_DEPARTURE) success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // BREACH(SHIP_DAMAGE) failure
        .mockReturnValue({ d20: 30, bonus: 0, diceNotation: '—', total: 30 })     // remaining events succeed
      rollDie.mockReturnValue(3)
      ShipService.damageShip.mockResolvedValue({ id: 1, status: 'broken', stats: { durability: 0, max_durability: 10 } })
      ConsumableService.consumeFromShipInventory.mockImplementation((client, shipId, effect) =>
        Promise.resolve(effect === 'REPAIR' ? { id: 9 } : null))

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(ShipService.damageShip).toHaveBeenCalledWith(expect.anything(), 1, 1, 3)
      expect(ShipService.repairShip).toHaveBeenCalledWith(expect.anything(), 1, 1)
      expect(updated.forced_return).toBe(false)
      expect(updated.event_results.find(r => r.consequence === 'SHIP_DAMAGE').shipAutoRepaired).toBe(true)
    })

    test('a SHIP_DAMAGE failure without a REPAIR item breaks the ship and forces a return', async () => {
      const instance = await launchSeededMission({
        id: SHIP_DAMAGE_TEMPLATE_ID,
        difficulty: 'PERILOUS',
        events: [
          buildEvent({ id: 'e1', type: 'RECON', attribute: 'perception', dc: 20, failureConsequence: 'HP_LOSS' }),
          buildEvent({ id: 'e2', type: 'BREACH', attribute: 'learning', dc: 30, failureConsequence: 'FORCED_DEPARTURE' }),
          buildEvent({ id: 'e3', type: 'BREACH', attribute: 'learning', dc: 30, failureConsequence: 'SHIP_DAMAGE' }),
        ],
      })
      instance.started_at = new Date(Date.now() - 10 * 60 * 1000)
      rollAction
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // RECON success
        .mockReturnValueOnce({ d20: 30, bonus: 0, diceNotation: '—', total: 30 }) // BREACH(FORCED_DEPARTURE) success
        .mockReturnValueOnce({ d20: 1, bonus: 0, diceNotation: '—', total: 1 })   // BREACH(SHIP_DAMAGE) failure
      rollDie.mockReturnValue(10)
      ShipService.damageShip.mockResolvedValue({ id: 1, status: 'broken', stats: { durability: 0, max_durability: 10 } })

      await GameService.syncGame()
      const updated = state.missionInstances[0]

      expect(ShipService.repairShip).not.toHaveBeenCalled()
      expect(updated.phase).toBe('RETURN')
      expect(updated.forced_return).toBe(true)
      expect(updated.event_results.at(-1).shipBroken).toBe(true)
    })
  })

  describe('stopMission', () => {
    test('releases crew and ship then deletes the mission in progress', async () => {
      await GameService.initGame()
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(1, 1)

      const result = await GameService.stopMission(1)

      expect(result.error).toBeUndefined()
      expect(state.missionInstances).toHaveLength(0)
      expect(state.recruits.find(r => r.id === 1).status).toBe('available')
      expect(ShipService.updateShipStatus).toHaveBeenCalledWith(expect.anything(), 1, 1, 'docked')
    })

    test('reports an error when no active mission matches', async () => {
      await GameService.initGame()
      const result = await GameService.stopMission(1)
      expect(result.error).toBe('No active mission')
    })
  })

  describe('forceReturnMission', () => {
    test('triggers a forced return on a mission in progress', async () => {
      await GameService.initGame()
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(1, 1)

      const result = await GameService.forceReturnMission(1)

      expect(result.error).toBeUndefined()
      expect(state.missionInstances[0].forced_return).toBe(true)
      expect(state.missionInstances[0].phase).toBe('RETURN')
    })

    test('refuses if no active mission matches', async () => {
      await GameService.initGame()
      const result = await GameService.forceReturnMission(1)
      expect(result.error).toBe('No active mission')
    })

    test('refuses a second forced return once RETURN phase is reached', async () => {
      await GameService.initGame()
      state.recruits[0].id = 1
      ShipService.getShip.mockResolvedValue({ id: 1, player_id: 1, crew: [1], status: 'docked', deleted_at: null })
      await GameService.startMission(1, 1)
      await GameService.forceReturnMission(1)

      const result = await GameService.forceReturnMission(1)
      expect(result.error).toBe('Return already in progress or mission completed')
    })
  })

  describe('refreshCandidates', () => {
    test('replaces all existing candidates with a new batch', async () => {
      await GameService.initGame()
      const previousIds = state.candidates.map(c => c.id)

      await GameService.refreshCandidates(3)

      expect(state.candidates).toHaveLength(3)
      expect(state.candidates.map(c => c.id)).not.toEqual(previousIds)
      expect(state.players[0].next_candidate_id).toBe(4)
    })
  })

  describe('renameRecruit', () => {
    test('renames an existing recruit', async () => {
      await GameService.initGame()
      const recruitId = state.recruits[0].id

      const result = await GameService.renameRecruit(String(recruitId), 'New Name')

      expect(result.error).toBeUndefined()
      expect(result.recruit.name).toBe('New Name')
      expect(state.recruits[0].name).toBe('New Name')
    })

    test('reports an error when the recruit cannot be found', async () => {
      await GameService.initGame()
      const result = await GameService.renameRecruit('99999', 'New Name')
      expect(result.error).toBe('Recruit not found')
    })
  })

  describe('getMissionLogs', () => {
    test('returns the logs of the requested mission for the default player', async () => {
      state.logEntries.push(
        { player_id: 1, mission_id: 1, tag: '[SYS]', message: 'Departure' },
        { player_id: 1, mission_id: 2, tag: '[SYS]', message: 'Other mission' },
      )
      pool.query.mockImplementation(async (sql, params) => {
        if (sql.includes('FROM log_entries') && sql.includes('mission_id = $2')) {
          return {
            rows: state.logEntries
              .filter(l => l.player_id === params[0] && l.mission_id === params[1])
              .map(({ tag, message }) => ({ tag, message })),
          }
        }
        throw new Error(`Query not handled: ${sql}`)
      })

      const logs = await GameService.getMissionLogs(1)

      expect(logs).toEqual([{ tag: '[SYS]', message: 'Departure' }])
    })
  })

  describe('getMissionHistory', () => {
    test('includes only templates that were started, tagged with their instance status', async () => {
      seedTemplate(state, { id: 1, events: [] })
      seedTemplate(state, { id: 2, events: [] })
      seedTemplate(state, { id: 3, events: [] }) // never started — must be excluded

      state.missionInstances.push(
        {
          id: 1000, player_id: 1, template_id: 1, ship_id: 5, status: 'success',
          phase: 'COMPLETED', progress: 100, current_event_index: 0, event_results: [],
          failed: false, reward_forfeited: false,
        },
        {
          id: 1001, player_id: 1, template_id: 2, ship_id: 7, status: 'failed',
          phase: 'COMPLETED', progress: 100, current_event_index: 0, event_results: [],
          failed: true, reward_forfeited: false,
        },
      )

      const history = await GameService.getMissionHistory()

      expect(history).toHaveLength(2)
      expect(history.find(m => m.id === 1)).toMatchObject({ status: 'success', assignedShipId: 5 })
      expect(history.find(m => m.id === 2)).toMatchObject({ status: 'failed', assignedShipId: 7 })
      expect(history.some(m => m.id === 3)).toBe(false)
    })

    test('reports an in-progress mission with its live status, not just success/failed', async () => {
      seedTemplate(state, { id: 4, events: [] })
      state.missionInstances.push({
        id: 1002, player_id: 1, template_id: 4, ship_id: 2, status: 'in_progress',
        phase: 'EVENT', progress: 40, current_event_index: 1, event_results: [],
        failed: false, reward_forfeited: false,
      })

      const history = await GameService.getMissionHistory()

      expect(history).toEqual([
        expect.objectContaining({ id: 4, status: 'in_progress', assignedShipId: 2 }),
      ])
    })

    test('returns an empty array when nothing has ever been started', async () => {
      seedTemplate(state, { id: 5, events: [] })

      const history = await GameService.getMissionHistory()

      expect(history).toEqual([])
    })

    test('only returns history for the requesting player, not other players\' instances', async () => {
      seedTemplate(state, { id: 6, events: [] })
      state.missionInstances.push({
        id: 1003, player_id: 999, template_id: 6, ship_id: 1, status: 'success',
        phase: 'COMPLETED', progress: 100, current_event_index: 0, event_results: [],
        failed: false, reward_forfeited: false,
      })

      const history = await GameService.getMissionHistory()

      expect(history).toEqual([])
    })
  })
})
