const { currentIntervalBoundary, isRefreshDue } = require('../src/utils/refreshWindow');

const FIFTEEN_MIN = 15 * 60 * 1000;

describe('currentIntervalBoundary', () => {
  test('floors to the most recent 15-minute wall-clock boundary', () => {
    // 2026-01-01T10:07:33Z -> floors to 10:00:00Z
    const now = new Date('2026-01-01T10:07:33Z');
    expect(new Date(currentIntervalBoundary(now, FIFTEEN_MIN)).toISOString()).toBe('2026-01-01T10:00:00.000Z');
  });

  test('floors 10:14:59.999Z down to 10:00:00Z (still the same window)', () => {
    const now = new Date('2026-01-01T10:14:59.999Z');
    expect(new Date(currentIntervalBoundary(now, FIFTEEN_MIN)).toISOString()).toBe('2026-01-01T10:00:00.000Z');
  });

  test('10:15:00.000Z is exactly the next boundary', () => {
    const now = new Date('2026-01-01T10:15:00.000Z');
    expect(new Date(currentIntervalBoundary(now, FIFTEEN_MIN)).toISOString()).toBe('2026-01-01T10:15:00.000Z');
  });

  test('accepts a raw ms timestamp as well as a Date', () => {
    const now = new Date('2026-01-01T10:37:00Z');
    expect(currentIntervalBoundary(now.getTime(), FIFTEEN_MIN)).toBe(currentIntervalBoundary(now, FIFTEEN_MIN));
  });
});

describe('isRefreshDue', () => {
  test('is due when nothing has ever been refreshed (null or undefined)', () => {
    const now = new Date('2026-01-01T10:07:00Z');
    expect(isRefreshDue(null, now, FIFTEEN_MIN)).toBe(true);
    expect(isRefreshDue(undefined, now, FIFTEEN_MIN)).toBe(true);
  });

  test('is not due when the last refresh happened in the same 15-minute window', () => {
    const lastRefresh = new Date('2026-01-01T10:00:00Z')
    const now = new Date('2026-01-01T10:14:59Z')
    expect(isRefreshDue(lastRefresh, now, FIFTEEN_MIN)).toBe(false)
  })

  test('is not due even 1ms before the next boundary', () => {
    const lastRefresh = new Date('2026-01-01T10:00:00.000Z')
    const now = new Date('2026-01-01T10:14:59.999Z')
    expect(isRefreshDue(lastRefresh, now, FIFTEEN_MIN)).toBe(false)
  })

  test('is due exactly at the next 15-minute boundary', () => {
    const lastRefresh = new Date('2026-01-01T10:00:00Z')
    const now = new Date('2026-01-01T10:15:00Z')
    expect(isRefreshDue(lastRefresh, now, FIFTEEN_MIN)).toBe(true)
  })

  test('is due if several windows have elapsed since the last refresh', () => {
    const lastRefresh = new Date('2026-01-01T10:00:00Z')
    const now = new Date('2026-01-01T13:20:00Z')
    expect(isRefreshDue(lastRefresh, now, FIFTEEN_MIN)).toBe(true)
  })

  test('accepts a string/serialized timestamp for lastRefreshAt (as it would come back from the DB)', () => {
    const now = new Date('2026-01-01T10:20:00Z')
    expect(isRefreshDue('2026-01-01T10:00:00.000Z', now, FIFTEEN_MIN)).toBe(true)
    // 10:16 is in the same [10:15, 10:30) window as `now` (10:20) -> not due.
    expect(isRefreshDue('2026-01-01T10:16:00.000Z', now, FIFTEEN_MIN)).toBe(false)
  })

  test('is not fooled by a lastRefreshAt that is mid-window but not exactly on a boundary', () => {
    // Simulates a timestamp that wasn't generated by currentIntervalBoundary
    // itself (e.g. a manual DB edit) — should still floor correctly.
    const lastRefresh = new Date('2026-01-01T10:06:42Z')
    const now = new Date('2026-01-01T10:14:00Z')
    expect(isRefreshDue(lastRefresh, now, FIFTEEN_MIN)).toBe(false)
  })
})
